### ISSUE TITLE
Friend request message expiration issue

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-messenger#172]
Currently when a user A sends a message to user B, user A's state would be set to `requestSent` and user B's state would be set to `requestReceived`.

Once user A sends the message, it has 72 hours before that message expires.

The problem occurs when this message expires. So going again with the flow above:
- user A sends to user B.
- user B doesn't reply for 72 hours.
- user A's message gets expired and the state gets set to `none`

What would happen if user B now clicks `accept` on the received friend request? User A's state would be `none` but user B's state would be `friends` which is incorrect behaviour.

**Comment by Mikunj** [comment]
We should try and see what this does currently in the app

**Comment by BeaudanBrown** [comment]
The problem here is that with the traditional signal protocol, you generate 100 or so prekeys at once and send them all to the server. Then your contacts can grab them as they please and start sessions. For us, however, we are only generating prekeys when we send a friend request. So if somebody was able to get hold of a prekey bundle that we have sent along to someone we are trying to add as a friend they could potentially force us to start a session with them, or at least void the prekey bundle that we have sent to our friend and force us to restart the friend request process.
We have found that the "ciphertext" that we get from a PREKEY_BUNDLE message (which is all signal protocol stuff that we don't touch) is actually itself another proto object that is housing the actual ciphertext body
```
message PreKeyWhisperMessage {
	optional uint32 registrationId = 5;
	optional uint32 preKeyId       = 1;
	optional uint32 signedPreKeyId = 6;
	optional bytes  baseKey        = 2;
	optional bytes  identityKey    = 3;
	optional bytes  message        = 4; // WhisperMessage
}
```
So the tentative plan currently is to peep into this proto in message_receiver (~line 734) before we pass it into the sessionCipher (which deletes the prekey bundle once the session has been established) and double check that it is using the correct preKeyId  for the contact pubKey that is trying to establish the session. Then we can just discard any messages that don't match.

Another thing which came up from looking into this is that this proto object, which isn't encrypted using the signal protocol, is usually encrypted with the `signallingKey` symmetric key that every user generates with the signal servers when they create their account. We have started discussing the pros and cons of doing similar encryption between users and the service nodes, and what that would look like (asymmetric encryption? Symmetric?)

**Comment by sachaaaaa** [comment]
@BeaudanBrown is this the right issue for your comment?
Sounds more like #173

**Comment by sachaaaaa** [comment]
One possible solution is to add a new state `requestTimedOut` which allows the user to re-send a new friend request but also allows to jump to `friends` in case it receives a friend request accepted.
In this case, the state `none` would only be used as a state initialising value.

**Comment by sachaaaaa** [comment]
Another option is to display the friend request as expired on the receiving end and prevent the user from accepting it. Either user would then be allowed to send a new friend request to each other.

**Comment by sachaaaaa** [comment]
Mmh after offline discussion with the team, the new `requestTimedOut` state is more user friendly.
