### ISSUE TITLE
Database error opening messenger 2nd time

### ISSUE THREAD

**Issue by Azazel020** [loki-project/loki-messenger#330]
**Describe the bug**
Opening the messenger for the 2nd time give me a database error. (it worked before)

**To Reproduce**
- Install messenger
- Open it/Close it and open it for the 2nd time

**Screenshots or Logs**

Database startup error:

Error: SQLITE_NOTADB: file is not a database

**Other information (please complete the following information):**

* Device: Laptop HP Pavilion
* OS: Windows 10
* Loki messenger Version or Git commit hash: 1.0.0-Beta1

**Comment by yidakee** [comment]
Same here, MacOS 10.14.5

`Database startup error:

Error: SQLITE_NOTADB: file is not a database`

Tried restoring from seed, but seems the seed is tied to the old password. I had no clue, or rushed it and didn't take notice. I am 99,95% I know my password, but it is not accepting it. Will have to create a new account

**Comment by Spootz** [comment]
Same Error as the above two. 

Device: i7 950, 12gb ram, AMD HD5880
Windows 7 Ultimate 64-Bit

![image](https://user-images.githubusercontent.com/52539868/60674123-fb0c6300-9eab-11e9-946d-ff64ec59baef.png)

Click the delete data button and it restarts the messenger. Reload the program and restore from seed... Loads the first reply from every conversation but nothing more. Asks to accept requests again for p2p messaging.

**Comment by crypto-ali** [comment]
Same error:

Database startup error:

Error: SQLITE_NOTADB: file is not a database
----
Worked fine on installation and initial start up. After quitting Loki Messenger and starting it up again a few minutes later. Got the error.
----
System Info:
Device: Dell XPS laptop
OS: Windows 10 Home 64bit
Program: Loki Messenger 1.0.0-Beta1

**Comment by yidakee** [comment]
History is not being preserved on app restart either.

**Comment by BeaudanBrown** [comment]
The friend request issue I understand, friend requests are encrypted with a simple Diffie–Hellman from the pubkeys, which is used to send the prekey bundle to the person you are sending the friend request to which is then used to establish the signal protocol session. Every session you establish uses several keys, including a one-time-use key

When you are destroying your database and then restoring from seed your previous conversations still exist in your swarm, but the only one your client is able to decrypt is the initial Diffie–Hellman friend request. Since the rest of the message history is encrypted with a now-destroyed session (established with an also now-destroyed one-time key) you aren't able to decrypt them

Also since the requests you sent are not linked to your pubkey on the storage server (only the recipient's) you aren't retrieving those (because it is assumed that you already have them locally because they are the ones you sent)

Complicated issues which we still need to figure out the best way to handle. Another difficulty is that all the messages on the storage server are temporary (default time to live of 24 hours currently) so a full history sync is never really possible, and since the signal protocol uses a ratcheting system which changes keys for essentially every message, you are required to parse every message to continue using an old session

But the real kick in the pants is that your contacts who haven't had their databases reset still think they have a valid session with you, so any messages they will be trying to send you will fail to decrypt on your end. Currently it *may* be possible for the person who reset their database to force the other contact to start a new session by sending a new friend request, but I would have to double check the code it isn't something I have tried recently. But the best bet currently is probably for both parties to delete each other locally (clearing all sessions from their databases) and then do another friend request exchange until we figure out a nice way to gracefully recover from session loss

As for the database error we will be trying to recreate and fix today, if anyone is suffering from this I'm not sure if there will be any logs available from such an early crash but if they could open the app and go to `view -> Debug Log -> Submit` and then post the link that is generated here (or message me `058131f605438547bf04c88587fd2bb0fbddc09156c14be828323011cf0595e676` :wink:) and I can have a peruse

It should remove any identifying information (such as usernames in directories etc)

**Comment by BeaudanBrown** [comment]
Alright I figured out the issue, the last upstream merge we did is catching an error we were using to determine that the database was password protected

Should have a fix today

**Comment by yidakee** [comment]
db issue fixed on MacOS with beta 2

**Comment by crypto-ali** [comment]
db issue fixed on Windows 10 for me.

**Comment by BeaudanBrown** [comment]
Fixed in beta 2 by #332
