### ISSUE TITLE
Reports "Disconnected check your network connection" all the while I am able to communicate

### ISSUE THREAD

**Issue by necro-nemesis** [loki-project/loki-messenger#334]
I installed beta 1 on Debian and Windows and both were working a day ago without the message. Today both installations came up with the message. I upgraded both to beta 2. Message still there. Jeff sent me a test message and we were able to communicate just fine but the connection message still remains and I don't appear to be able to clear it.

**Comment by necro-nemesis** [comment]
![image](https://user-images.githubusercontent.com/29291956/60729568-0c3b8b00-9f11-11e9-859c-5b603de857e3.png)

**Comment by BeaudanBrown** [comment]
Hm I have a couple hunches about this
It could potentially be an issue with the nodes in your swarm. We are trying to maintain a connection with 3 nodes, and if there are only 2 nodes in your swarm servicing requests (I have noticed a few nodes here and there being unresponsive or respond with 400 which is caused by their lokid failing to sync) then the return function is reporting connection errors. This is a bit tricky because it's definitely strange to be showing this error while technically you are still able to send/retrieve messages, we should maybe look into a different message to display for limited connection.

Another possible issue could be this snippet:
```js
} else if (e instanceof textsecure.NotFoundError) {
  // DNS/Lokinet error, needs to bubble up
  throw new window.textsecure.DNSResolutionError(
      'Retrieving messages'
  );
}
```
Which originated from when we were developing the messenger with lokinet integration and this error would indicate a lokinet connection issue and we would abort early and display disconnected if any of your connections reported this error
So potentially there is another issue causing this error to trigger?

At any rate it would be great if you could open the app and go to `View -> Debug Log -> Submit` and post/send me the link it generates please

**Comment by necro-nemesis** [comment]
I have 2 instances of the same account running. One Windows the other Debian. I removed and cleared the information then recovered via phrase on the Debian. That seem to have cleared it reporting the connection issue. Windows version I haven't messed with so it should have the Debug Log intact with the issue.

**Comment by necro-nemesis** [comment]
Debug from JoeyJoeyJoey who reported the same error message today.

https://debuglogs.org/2662272092b8d87ddb86bc492148748a9471044d3e747d5e1b23dc9e8a21abae

**Comment by BeaudanBrown** [comment]
Ah I think I know one of the potential problems
He got a `WrongSwarmError` which usually indicates that they had been using the app some time in the past and then hadn't opened it for a while so the swarm state has changed since then
And we forgot to filter out `0.0.0.0` addresses (which is what lokid reports if it hasn't received an uptime proof from that node so it doesn't know it's ip/port) when we update swarms through the wrong swarm error. So he is reporting a bunch of `request to https://0.0.0.0:0/storage_rpc/v1 failed, reason: connect EADDRNOTAVAIL`
The latest storage server should be filtering these out on the other end so there might be some outdated storage server binaries on the testnet. Plus there were way too many failed requests which pointed me to another bug where checking with this magic number in one place
```js
if (successiveFailures >= 3) {
  await lokiSnodeAPI.unreachableNode(this.ourKey, address);
}
```
And then with this constant `const MAX_ACCEPTABLE_FAILURES = 1;` in other places so we were never actually purging the failed nodes for retrieving connections

Very useful logs, tyvm
Hopefully PR coming up should fix

**Comment by necro-nemesis** [comment]
Good. I will close the issue and if it reoccurs open it with a new log file attached.

**Comment by BeaudanBrown** [comment]
I'll actually leave this open until I am sure my patch is actually addressing this issue

**Comment by necro-nemesis** [comment]
Sounds good.
