### ISSUE TITLE
[multi-device] TODO

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#546]
- [ ] Friend requests between a paired device and a third-party pubkey are not propagated to the other paired devices
- [ ] Refresh device mappings for active conversations periodically
- [ ] Extract function to get all device mappings (secondary mappings are used to get the primary device pubkey, then get the latter's mapping)

**Comment by BeaudanBrown** [comment]
Ensure that we don't send messages to secondary devices that are pending friends

**Comment by BeaudanBrown** [comment]
Plan for initial friend request steps

- When adding contact for the first time, ignore other devices until session is established
- When sending messages to a friend, duplicate that message to all devices *with* established sessions, and check interval since last friend request was sent to devices *without* established sessions and send pre-generated friend request if it was a long time ago

**Comment by neuroscr** [comment]
> Extract function to get all device mappings (secondary mappings are used to get the primary device pubkey, then get the latter's mapping)

My multi-device public chat PR may have some library functions for this
